### ISSUE TITLE
Disks' storage components don't drop when dismantling [BUG?]

### ISSUE THREAD

**Issue by scorevi** [Lapis256/AE2MEGAThings#1]
https://youtu.be/WE9dP5Kp2iI

When dismantling a disk drive, its storage component doesn't drop/gets voided. Is this a bug or intentional..?

Minecraft version is 1.20.1

**Comment by Lapis256** [comment]
Thank you for your report.  
This bug has been fixed in version **v1.0.3**.  
Please update and confirm if the issue is resolved.  
Let us know if you encounter any other problems!
